services:
  backend:
    image: eminik/eneba-backend:latest
    container_name: backend
    restart: always

  frontend:
    image: eminik/eneba-frontend:latest
    container_name: frontend
    depends_on:
      - backend
    restart: always

