services:
  backend:
    image: eminik/eneba-backend:latest
    container_name: backend
    networks: 
      shared-services: 
        aliases: 
          - backend
    restart: always

  frontend:
    image: eminik/eneba-frontend:latest
    container_name: frontend
    networks: 
      shared-services: 
        aliases: 
          - frontend
    depends_on:
      - backend
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx_gateway
    networks:
      shared-services:
        aliases:
          - nginx_gateway
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - frontend

networks: 
  shared-services: 
    external: true 
    name: shared-services